labels_mapillary_seg = ClassDefinitions([
    #       name                         id    trainId   category            catId     hasInstances   ignoreInEval  color
    Label(  'car mount'                ,  0 ,      255 , 'void'            , 0       , False        , True        , ( 32, 32, 32) ),
    Label(  'ego vehicle'              ,  1 ,      255 , 'void'            , 0       , False        , True        , (120, 10, 10) ),
    Label(  'unlabeled'                ,  2 ,      255 , 'void'            , 0       , False        , True        , (  0,  0,  0) ),
    Label(  'barrier'                  ,  3 ,        0 , 'construction'    , 2       , False        , False       , ( 90,120,150) ),
    Label(  'bike lane'                ,  4 ,        1 , 'construction'    , 2       , False        , False       , (128, 64,255) ),
    Label(  'bridge'                   ,  5 ,        2 , 'construction'    , 2       , False        , False       , (150,100,100) ),
    Label(  'building'                 ,  6 ,        3 , 'construction'    , 2       , False        , False       , ( 70, 70, 70) ),
    Label(  'crosswalk - plain'        ,  7 ,        4 , 'construction'    , 2       , True         , False       , (140,140,200) ),
    Label(  'curb'                     ,  8 ,        5 , 'construction'    , 2       , False        , False       , (196,196,196) ),
    Label(  'curb cut'                 ,  9 ,        6 , 'construction'    , 2       , False        , False       , (170,170,170) ),
    Label(  'fence'                    , 10 ,        7 , 'construction'    , 2       , False        , False       , (190,153,153) ),
    Label(  'guard rail'               , 11 ,        8 , 'construction'    , 2       , False        , False       , (180,165,180) ),
    Label(  'parking'                  , 12 ,        9 , 'construction'    , 2       , False        , False       , (250,170,160) ),
    Label(  'pedestrian area'          , 13 ,       10 , 'construction'    , 2       , False        , False       , ( 96, 96, 96) ),
    Label(  'rail track'               , 14 ,       11 , 'construction'    , 2       , False        , False       , (230,150,140) ),
    Label(  'road'                     , 15 ,       12 , 'construction'    , 2       , False        , False       , (128, 64,128) ),
    Label(  'service lane'             , 16 ,       13 , 'construction'    , 2       , False        , False       , (110,110,110) ),
    Label(  'sidewalk'                 , 17 ,       14 , 'construction'    , 2       , False        , False       , (244, 35,232) ),
    Label(  'tunnel'                   , 18 ,       15 , 'construction'    , 2       , False        , False       , (150,120, 90) ),
    Label(  'wall'                     , 19 ,       16 , 'construction'    , 2       , False        , False       , (102,102,156) ),
    Label(  'banner'                   , 20 ,       17 , 'object'          , 3       , True         , False       , (255,255,128) ),
    Label(  'bench'                    , 21 ,       18 , 'object'          , 3       , True         , False       , (250,  0, 30) ),
    Label(  'bicycle'                  , 22 ,       19 , 'object'          , 3       , True         , False       , (119, 11, 32) ),
    Label(  'bike rack'                , 23 ,       20 , 'object'          , 3       , True         , False       , (100,140,180) ),
    Label(  'billboard'                , 24 ,       21 , 'object'          , 3       , True         , False       , (220,220,220) ),
    Label(  'boat'                     , 25 ,       22 , 'object'          , 3       , True         , False       , (150,  0,255) ),
    Label(  'bus'                      , 26 ,       23 , 'object'          , 3       , True         , False       , (  0, 60,100) ),
    Label(  'cctv camera'              , 27 ,       24 , 'object'          , 3       , True         , False       , (222, 40, 40) ),
    Label(  'car'                      , 28 ,       25 , 'object'          , 3       , True         , False       , (  0,  0,142) ),
    Label(  'caravan'                  , 29 ,       26 , 'object'          , 3       , True         , False       , (  0,  0, 90) ),
    Label(  'catch basin'              , 30 ,       27 , 'object'          , 3       , True         , False       , (220,128,128) ),
    Label(  'fire hydrant'             , 31 ,       28 , 'object'          , 3       , True         , False       , (100,170, 30) ),
    Label(  'junction box'             , 32 ,       29 , 'object'          , 3       , True         , False       , ( 40, 40, 40) ),
    Label(  'mailbox'                  , 33 ,       30 , 'object'          , 3       , True         , False       , ( 33, 33, 33) ),
    Label(  'manhole'                  , 34 ,       31 , 'object'          , 3       , True         , False       , (100,128,160) ),
    Label(  'motorcycle'               , 35 ,       32 , 'object'          , 3       , True         , False       , (  0,  0,230) ),
    Label(  'on rails'                 , 36 ,       33 , 'object'          , 3       , False        , False       , (  0, 80,100) ),
    Label(  'other vehicle'            , 37 ,       34 , 'object'          , 3       , True         , False       , (128, 64, 64) ),
    Label(  'phone booth'              , 38 ,       35 , 'object'          , 3       , True         , False       , (142,  0,  0) ),
    Label(  'pole'                     , 39 ,       36 , 'object'          , 3       , True         , False       , (153,153,153) ),
    Label(  'pothole'                  , 40 ,       37 , 'object'          , 3       , False        , False       , ( 70,100,150) ),
    Label(  'street light'             , 41 ,       38 , 'object'          , 3       , True         , False       , (210,170,100) ),
    Label(  'traffic light'            , 42 ,       39 , 'object'          , 3       , True         , False       , (250,170, 30) ),
    Label(  'traffic sign (back)'      , 43 ,       40 , 'object'          , 3       , True         , False       , (192,192,192) ),
    Label(  'traffic sign (front)'     , 44 ,       41 , 'object'          , 3       , True         , False       , (220,220,  0) ),
    Label(  'traffic sign frame'       , 45 ,       42 , 'object'          , 3       , True         , False       , (128,128,128) ),
    Label(  'trailer'                  , 46 ,       43 , 'object'          , 3       , True         , False       , (  0,  0,110) ),
    Label(  'trash can'                , 47 ,       44 , 'object'          , 3       , True         , False       , (140,140, 20) ),
    Label(  'truck'                    , 48 ,       45 , 'object'          , 3       , True         , False       , (  0,  0, 70) ),
    Label(  'utility pole'             , 49 ,       46 , 'object'          , 3       , True         , False       , (  0,  0, 80) ),
    Label(  'wheeled slow'             , 50 ,       47 , 'object'          , 3       , True         , False       , (  0,  0,192) ),
    Label(  'mountain'                 , 51 ,       48 , 'nature'          , 4       , False        , False       , ( 64,170, 64) ),
    Label(  'sand'                     , 52 ,       49 , 'nature'          , 4       , False        , False       , (230,160, 50) ),
    Label(  'sky'                      , 53 ,       50 , 'nature'          , 4       , False        , False       , ( 70,130,180) ),
    Label(  'snow'                     , 54 ,       51 , 'nature'          , 4       , False        , False       , (190,255,255) ),
    Label(  'terrain'                  , 55 ,       52 , 'nature'          , 4       , False        , False       , (152,251,152) ),
    Label(  'vegetation'               , 56 ,       53 , 'nature'          , 4       , False        , False       , (107,142, 35) ),
    Label(  'water'                    , 57 ,       54 , 'nature'          , 4       , False        , False       , (  0,170, 30) ),
    Label(  'bicyclist'                , 58 ,       55 , 'human'           , 6       , True         , False       , (255,  0,  0) ),
    Label(  'motorcyclist'             , 59 ,       56 , 'human'           , 6       , True         , False       , (255,  0,100) ),
    Label(  'other rider'              , 60 ,       57 , 'human'           , 6       , True         , False       , (255,  0,200) ),
    Label(  'person'                   , 61 ,       58 , 'human'           , 6       , True         , False       , (220, 20, 60) ),
    Label(  'lane marking - crosswalk' , 62 ,       59 , 'marking'         , 8       , True         , False       , (200,128,128) ),
    Label(  'lane marking - general'   , 63 ,       60 , 'marking'         , 8       , False        , False       , (255,255,255) ),
    Label(  'bird'                     , 64 ,       61 , 'animal'          , 9       , True         , False       , (165, 42, 42) ),
    Label(  'ground animal'            , 65 ,       62 , 'animal'          , 9       , True         , False       , (  0,192,  0) ),
])
